languageCode = "zh-tw"
languageName = "繁體中文"
weight = 1
title = "Research Data Management Hub"

[params]
  displayName = "繁體中文"
  isoCode = "zh-TW"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "logo.svg"
