[[main]]
  name = "資源"
  pageRef = "resources"
  weight = 10

[[main]]
  name = "實踐"
  pageRef = "showcases"
  weight = 20

[[main]]
  name = "消息"
  pageRef = "news"
  weight = 30

[[main]]
  name = "關於"
  pageRef = "about"
  weight = 40

[[main]]
  identifier = "youtube"
  pre = "youtube"
  weight = 50
  url = "https://www.youtube.com/@depositar"

[[main]]
  identifier = "mastodon"
  pre = "mastodon"
  weight = 60
  url = "https://social.coop/@depositar"

[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 10

[[footer]]
  name = "Languages"
  pageRef = "languages"
  weight = 10